### PR TITLE
Update ProActive Agent Linux documentation

### PR DESCRIPTION
**Pull request by lpellegr**

### CODE REVIEW

**Comment by lpellegr** [comment]
@ow2-proactive/developers Could two people please review the changes?

**Comment by tobwiens** [comment]
Very nice :+1:

**Comment by lpellegr** [comment]
@tobwiens Thank you. Typo fixed.

One more review required before merging.

**Comment by cdiop** [comment]
Cool
OK for me

**Comment by lpellegr** [comment]
@cdiop Thx

**Pull request merged**
