### PR TITLE
Upgrade to Gradle 6.8.3 and various minor fixes

### PR DESCRIPTION
**Pull request by amottier**
This is an attempt to update to more recent version of Gradle to be able to use Java 11 to run Gradle.

- Upgrade Gradle wrapper from version 3.3 to version 6.8.3. Not possible to upgrade to version 7.0 due to incompatible plugin (see https://github.com/aim42/htmlSanityCheck/issues/282 should be fixed in htmlSanityCheck plugin version 1.1.4).
- Keep only Xalan as build script dependency.
- Include plugins using the `plugins` block instead of `apply` approach.
- Added `baseDirFollowsSourceFile()` to asciidoctor configuration to fix issue relate to `include` directive with the new plugin version.
- Update `asciidoctorj` to latest version.
- Bump plugins to latest versions.
- Removed unused repository.
- Fix links in `reference.adoc` to "Customize the service section" (was missing path to the HTML file).
- Fix link (invalid character) in `ProActiveAdminGuide.adoc`.
- Fix links (avoid HTTP -> HTTPS redirection) and update URL for PyTorch torchvision documentation in `PMLUserGuide.adoc`.
- Use `maven-publish` plugin instead of `maven` (can probably be removed).
- IMPORTANT: replaced in `PMLUserGuide.adoc` https://s3.eu-west-2.amazonaws.com/activeeon-public/datasets/pascal_coco.zip by https://s3.eu-west-2.amazonaws.com/activeeon-public/datasets/ as `pascal_coco.zip` seems to be missing.

### CODE REVIEW

**Comment by fviale** [comment]
Retest this please

**Review by fviale — APPROVED** [review]
LGTM

**Review by mboussaa — APPROVED** [review]
could you please change  https://s3.eu-west-2.amazonaws.com/activeeon-public/datasets/pascal_coco.zip by https://s3.eu-west-2.amazonaws.com/activeeon-public/datasets/coco.zip

**Comment by fviale** [comment]
@amottier  unfortunately, the change has been applied on the master by another developper, can you fix the conflict ?

**Comment by amottier** [comment]
> could you please change https://s3.eu-west-2.amazonaws.com/activeeon-public/datasets/pascal_coco.zip by https://s3.eu-west-2.amazonaws.com/activeeon-public/datasets/coco.zip

@mboussaa I fix the link as requested but it seems it was also already update as part of bb780cb

**Comment by fviale** [comment]
@amottier yes, a lack of communication in our team, sorry for the inconvenience !

**Comment by amottier** [comment]
> @amottier yes, a lack of communication in our team, sorry for the inconvenience !

No worries and on my side I didn't properly fix the link on my first commit so I just amend it.

**Pull request merged**
